FROM eclipse-temurin:21-jdk as build

WORKDIR /app

COPY . .

RUN chmod +x ./mvnw
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/listas-api-1.0.0-SNAPSHOT-runner.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
